package com.proartz.Chapter5.Exercise7;

import java.nio.file.Paths;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        /*
        * Jeżeli na wskutek wystąpienia wyjątku w klauzuli try z zasobami,
        * podczas automatycznego zamykania zasobu wystąpi inny wyjątek,
        * pierwszy wyjątek(na wskutek którego nastąpła próba zamykania zasobu) jest ponownie
        * wyrzucany, a wyjątek związany z zamykaniem zasobu jest przechwytywany i dołączany
        * jako wyjątek wyciszony.
        * */

    }

}
